# Generated by Django 4.2.30 on 2026-06-02 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('property_type', models.CharField(choices=[('TEXT', 'Text'), ('DATETIME', 'Datetime'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('OPTION', 'Option'), ('RELATION', 'Relation'), ('URL', 'URL'), ('EMAIL', 'Email'), ('FILE', 'File'), ('FORMULA', 'Formula')], max_length=50)),
                ('relation_type', models.CharField(blank=True, choices=[('ISSUE', 'Issue'), ('USER', 'User')], max_length=50, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_multi', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(default=dict)),
                ('formula_config', models.TextField(blank=True, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.issuetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property',
                'verbose_name_plural': 'Issue Properties',
                'db_table': 'issue_properties',
                'ordering': ('sort_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.issuepropertyoption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Option',
                'verbose_name_plural': 'Issue Property Options',
                'db_table': 'issue_property_options',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Value',
                'verbose_name_plural': 'Issue Property Values',
                'db_table': 'issue_property_values',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyValueItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_value_items', to='db.fileasset')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_value_items', to='db.issue')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_items', to='db.issuepropertyoption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_items', to='db.issueproperty')),
                ('related_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_property_value_items', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_value_items', to=settings.AUTH_USER_MODEL)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.issuepropertyvalue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Value Item',
                'verbose_name_plural': 'Issue Property Value Items',
                'db_table': 'issue_property_value_items',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['project', 'property', 'deleted_at'], name='issue_prop_item_project_idx'), models.Index(fields=['issue', 'property', 'deleted_at'], name='issue_prop_item_issue_idx'), models.Index(fields=['property', 'option', 'deleted_at'], name='issue_prop_item_option_idx'), models.Index(fields=['property', 'user', 'deleted_at'], name='issue_prop_item_user_idx'), models.Index(fields=['property', 'related_issue', 'deleted_at'], name='issue_prop_item_rel_issue_idx'), models.Index(fields=['property', 'decimal_value', 'deleted_at'], name='issue_prop_item_decimal_idx'), models.Index(fields=['property', 'datetime_value', 'deleted_at'], name='issue_prop_item_datetime_idx'), models.Index(fields=['property', 'boolean_value', 'deleted_at'], name='issue_prop_item_boolean_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='issuepropertyvalue',
            index=models.Index(fields=['project', 'property', 'deleted_at'], name='issue_prop_value_project_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepropertyvalue',
            index=models.Index(fields=['issue', 'property', 'deleted_at'], name='issue_prop_value_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'property'), name='issue_property_value_unique_issue_property_active'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('external_id__isnull', False), ('external_source__isnull', False)), fields=('project', 'external_source', 'external_id'), name='issue_property_value_unique_external_active'),
        ),
        migrations.AddIndex(
            model_name='issuepropertyoption',
            index=models.Index(fields=['project', 'property', 'deleted_at'], name='issue_prop_option_project_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepropertyoption',
            index=models.Index(fields=['property', 'is_active', 'deleted_at'], name='issue_prop_option_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('property', 'name'), name='issue_property_option_unique_name_active'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('external_id__isnull', False), ('external_source__isnull', False)), fields=('property', 'external_source', 'external_id'), name='issue_property_option_unique_external_active'),
        ),
        migrations.AddIndex(
            model_name='issueproperty',
            index=models.Index(fields=['project', 'issue_type', 'deleted_at'], name='issue_prop_project_type_idx'),
        ),
        migrations.AddIndex(
            model_name='issueproperty',
            index=models.Index(fields=['project', 'name', 'deleted_at'], name='issue_prop_project_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type', 'name'), name='issue_property_unique_type_name_active'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type', 'display_name'), name='issue_property_unique_type_display_active'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('external_id__isnull', False), ('external_source__isnull', False)), fields=('project', 'issue_type', 'external_source', 'external_id'), name='issue_property_unique_type_external_active'),
        ),
    ]
